import * as fs from 'fs';
import * as path from 'path';
import * as vscode from 'vscode';
import { getOutputChannel } from './cli-runner.js';
import { getActiveContext, getGroupDetails, listIndexedRepos } from './group-context.js';

const ACTIVE_SCOPE_SKILL_RELATIVE_PATH = path.join(
  '.github',
  'skills',
  'gitnexus-active-scope',
  'SKILL.md',
);

function resolveToolRepoValue(active: ReturnType<typeof getActiveContext>): string | undefined {
  if (!active) {
    return undefined;
  }

  return active.type === 'group' ? `@${active.name}` : active.name;
}

async function renderSkill(active: ReturnType<typeof getActiveContext>): Promise<string> {
  const toolRepoValue = resolveToolRepoValue(active);
  const typeLabel = active?.type ?? 'none';
  const nameLabel = active?.name ?? '(not set)';
  const repoLabel = toolRepoValue ?? '(not set)';
  const lines = [
    '---',
    'name: gitnexus-active-scope',
    'description: "Use this skill to let GitNexus tools know the user\'s current active repo/group context."',
    '---',
    '',
    '# GitNexus Active Scope',
    '',
    'This file is auto-generated by the CodeBrain VS Code extension.',
    'Do not edit this file manually because it is refreshed when active context changes.',
    '',
    '## Current Active Context',
    `- Type: ${typeLabel}`,
    `- Name: ${nameLabel}`,
    `- Default repo argument for GitNexus MCP tools: ${repoLabel}`,
  ];

  if (active?.type === 'group') {
    const group = await getGroupDetails(active.name);
    const indexedRepos = await listIndexedRepos();

    lines.push('');
    lines.push('## Repositories In Active Group');

    if (!group || Object.keys(group.repos).length === 0) {
      lines.push('- (no repositories found in group)');
    } else {
      for (const [groupPath, registryName] of Object.entries(group.repos)) {
        const matchedRepo = indexedRepos.find((repo) => repo.name === registryName);
        const repoFsPath = matchedRepo?.path ?? '(not indexed in current workspace)';
        lines.push(`- ${groupPath} -> ${registryName} | path: ${repoFsPath}`);
      }
    }
  }

  lines.push('');
  lines.push('## Agent Rules');
  lines.push('1. If the user does not specify a repo/group, use the default repo argument above for GitNexus tools that support `repo`.');
  lines.push('2. For group context, keep the `@group` form exactly as shown in this file.');
  lines.push('3. If no active context is set, first discover repos with `mcp_gitnexus_list_repos` and ask the user to choose scope.');

  return lines.join('\n');
}

function writeSkillFile(workspaceRoot: string, content: string): boolean {
  const skillFile = path.join(workspaceRoot, ACTIVE_SCOPE_SKILL_RELATIVE_PATH);
  const skillDir = path.dirname(skillFile);

  fs.mkdirSync(skillDir, { recursive: true });

  if (fs.existsSync(skillFile)) {
    const current = fs.readFileSync(skillFile, 'utf8');
    if (current === content) {
      return false;
    }
  }

  fs.writeFileSync(skillFile, content, 'utf8');
  return true;
}

/**
 * Sync a generated Copilot skill that advertises the active GitNexus repo/group scope.
 */
export async function syncActiveContextSkill(storage: vscode.Memento): Promise<void> {
  const folders = vscode.workspace.workspaceFolders ?? [];
  if (folders.length === 0) {
    return;
  }

  const active = getActiveContext(storage);
  const content = await renderSkill(active);
  const output = getOutputChannel();

  for (const folder of folders) {
    try {
      const changed = writeSkillFile(folder.uri.fsPath, content);
      if (changed) {
        output.appendLine(
          `CodeBrain: Updated active-scope skill at ${path.join(folder.uri.fsPath, ACTIVE_SCOPE_SKILL_RELATIVE_PATH)}`,
        );
      }
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      output.appendLine(
        `CodeBrain: Failed to update active-scope skill in ${folder.uri.fsPath}: ${message}`,
      );
    }
  }
}
